language: python
dist: xenial
sudo: true
python:
  - "3.6"
  - "3.7"

env:
  global:
    - PIPENV_IGNORE_VIRTUALENVS=1

install:
  - make dependencies

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - pipenv check
  - pipenv run make test

after_script:
  - pipenv run coverage xml
  - ./cc-test-reporter after-build -t coverage.py --exit-code $TRAVIS_TEST_RESULT

# automated pypi releases
deploy:
  provider: pypi
  user: eduk
  on:
    branch: master
    tags: true
  distributions: sdist bdist_wheel
