language: python
sudo: false
python:
  - "3.6"

install:
  - pip install -U pip --no-cache-dir
  - pip install pipenv
  - pipenv install --dev

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - make test

after_script:
  - coverage xml
  - ./cc-test-reporter after-build -t coverage.py --exit-code $TRAVIS_TEST_RESULT

# automated pypi releases
deploy:
  provider: pypi
  user: eduk
  on:
    branch: master
    tags: true
  distributions: sdist bdist_wheel
